name: Actionlint

on:
  pull_request:
    branches: [main, develop]
    paths:
      - ".github/workflows/**"
  push:
    branches: [main, develop]
    paths:
      - ".github/workflows/**"

permissions:
  contents: read

jobs:
  actionlint:
    name: Actionlint (Workflow Validation)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4

      - name: Run actionlint
        uses: raven-actions/actionlint@205b530c5d9fa8f44ae9ed59f341a0db994aa6f8 # v2
        with:
          matcher: true
