name: OSSF Scorecard

on:
  schedule:
    - cron: "15 6 * * 1"
  push:
    branches: [main]
  workflow_dispatch:

permissions: read-all

jobs:
  scorecard:
    name: OSSF Scorecard Analysis
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Run OSSF Scorecard
        uses: ossf/scorecard-action@f49a007a1820db6ceebb72793b5702863597feac # v2.4.0
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload Scorecard SARIF
        uses: github/codeql-action/upload-sarif@83f53effe54e4c278e34898246f6f1947b198118 # v3.25.7
        with:
          sarif_file: results.sarif
